#!/usr/bin/env bun
import {
  existsSync, mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { block } from "./blocks.mjs";
import { canonicalRoleId, containedLeaf } from "./role-id.mjs";
import { effectiveFilesystemAuthority, loadStaffingCatalog } from "./staffing-catalog.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (path) => readFileSync(resolve(ROOT, path), "utf8");
const yamlString = (value) => JSON.stringify(String(value));

const SOURCES = Object.freeze({
  staffing: "staffing/catalog.json",
  roles: "docs/roles.md",
  taskGrades: "docs/task-grades.md",
  topologies: "docs/topologies.md",
  postures: "docs/postures.md",
  comms: "docs/comms.md",
});
export const AGENT_SOURCE_PATHS = Object.freeze(Object.values(SOURCES));

export function renderAgent(preset) {
  const filesystem = effectiveFilesystemAuthority(preset.capabilities);
  const routing = {
    role: preset.name,
    taskGrade: preset.taskGrade,
    domainRequirements: [],
    topology: preset.topology,
    capabilityFloor: preset.capabilityFloor,
    serviceClass: preset.serviceClass,
    reasoning: preset.deliberation,
    posture: preset.posture,
    composition: { kind: "template", id: preset.name, overrides: [] },
  };
  const sections = [
    "---",
    `name: ${yamlString(preset.name)}`,
    `description: ${yamlString(`${preset.description} Task grade: ${preset.taskGrade}.`)}`,
    "---",
    "",
    "<!-- GENERATED by agent-machinery:scripts/build-agents.mjs. Edit source blocks or agent-machinery:staffing/catalog.json. -->",
    `<!-- AGENT_RUN_ROUTING ${JSON.stringify(routing)} -->`,
    `<!-- AGENT_RUN_CAPABILITIES ${JSON.stringify(preset.capabilities)} -->`,
    "",
    `You are the ${preset.name}: ${preset.tagline}.`,
    "",
    "## Role",
    block(read(SOURCES.roles), preset.name),
    "",
    `## Task grade: ${preset.taskGrade}`,
    block(read(SOURCES.taskGrades), preset.taskGrade),
    "",
    `## Topology: ${preset.topology}`,
    block(read(SOURCES.topologies), preset.topology),
    "",
    `## Posture: ${preset.posture}`,
    block(read(SOURCES.postures), preset.posture),
    "",
    "## Canonical capabilities",
    ...preset.capabilities.map((capability) => `- \`${capability}\``),
    "",
    "## Effective filesystem authority",
    `- read: ${filesystem.read ? "allowed" : "denied"}`,
    `- search: ${filesystem.search ? "allowed" : "denied"}`,
    `- write: ${filesystem.write ? "allowed" : "denied"}`,
    "",
    "`shell` conveys filesystem read, search, and write authority. `shell.readonly` conveys read and search authority only and requires shell execution whose filesystem writes are denied. If this effective authority cannot be enforced, fail closed and do not run this agent.",
    "",
    "## Output norms",
    block(read(SOURCES.comms), "universal"),
    "",
  ];
  return sections.join("\n");
}

export function buildAgents({ check = false } = {}) {
  const catalog = loadStaffingCatalog(resolve(ROOT, SOURCES.staffing));
  const outputRoot = resolve(ROOT, "agents");
  mkdirSync(outputRoot, { recursive: true });
  const expected = new Set();
  const stale = [];

  for (const preset of catalog.presets) {
    const id = canonicalRoleId(preset.name);
    const filename = `${id}.md`;
    expected.add(filename);
    const path = containedLeaf(outputRoot, filename, `generated agent ${id}`);
    const rendered = renderAgent(preset);
    const current = existsSync(path) ? readFileSync(path, "utf8") : "";
    if (current === rendered) continue;
    if (check) stale.push(`agents/${filename}`);
    else {
      writeFileSync(path, rendered);
      process.stdout.write(`wrote agents/${filename}\n`);
    }
  }

  for (const filename of existsSync(outputRoot) ? readdirSync(outputRoot) : []) {
    if (!filename.endsWith(".md") || expected.has(filename)) continue;
    if (check) stale.push(`agents/${filename}`);
    else {
      unlinkSync(containedLeaf(outputRoot, filename));
      process.stdout.write(`removed agents/${filename}\n`);
    }
  }

  if (stale.length) throw new Error(`stale generated templates: ${stale.join(", ")}`);
  return [...expected].sort();
}

const invoked = process.argv[1] &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href;
if (invoked) {
  try {
    const files = buildAgents({ check: process.argv.includes("--check") });
    process.stdout.write(`${process.argv.includes("--check") ? "check" : "build"}: ${files.length} templates current\n`);
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}
