#!/usr/bin/env bash
# ============================================================================
# North R-1 apparatus driver — TEST-ONLY, non-production. Two cells:
#   1. cross-repo/cross-runtime identity: North's JS K_ev oracle must reproduce
#      the golden vector byte-for-byte (generated by fram's bb/JVM oracle),
#      proving bb==JVM==JS agree ACROSS repos on the raw-byte identity law.
#   2. §4 attribution: the four-envelope precedence + legacy :frame law, RED
#      against the revoked B-prime order, GREEN against current North source.
# Exits nonzero on any unexpected verdict. No daemon, no port, no live state.
# ============================================================================
set -u
cd "$(dirname "$0")"
FAIL=0

echo "########## cross-repo identity oracle (North JS vs fram golden) ##########"
for MODEL in b2 bprime; do
  node kev.mjs "$MODEL" corpus/coordination.log corpus/telemetry.log > "corpus/js.$MODEL.tsv"
  if diff -q "corpus/js.$MODEL.tsv" "corpus/golden.$MODEL.tsv" >/dev/null; then
    echo "  JS==GOLDEN ($MODEL) — North JS reproduces fram's K_ev vector byte-for-byte"
  else
    echo "  JS!=GOLDEN ($MODEL)"; diff "corpus/js.$MODEL.tsv" "corpus/golden.$MODEL.tsv"; FAIL=1
  fi
done
# S1 divergence receipt (same as fram): B2 keeps tx=2 twice, B-prime once.
b2n=$(grep -c '^2	' corpus/js.b2.tsv); bpn=$(grep -c '^2	' corpus/js.bprime.tsv)
echo "  S1 tx=2 multiplicity — B2=$b2n (expect 2) B-prime=$bpn (expect 1)"
[ "$b2n" = 2 ] && [ "$bpn" = 1 ] || { echo "  S1 DIVERGENCE UNEXPECTED"; FAIL=1; }

echo; echo "########## §4 attribution reference model ##########"
if node attribution.mjs; then echo ">>> attribution: OK"; else echo ">>> attribution: UNEXPECTED"; FAIL=1; fi

# negative control: harness must fail loud.
echo; echo "########## negative control (must exit nonzero) ##########"
if node -e '
import("./harness.mjs").then(h => { h.check("INTENTIONALLY-FALSE", 1, 2); h.finish(); });
' >/dev/null 2>&1; then
  echo ">>> negative control DID NOT FAIL — harness untrustworthy"; FAIL=1
else
  echo ">>> negative control failed loud as required (self-check OK)"
fi

echo
if [ "$FAIL" -eq 0 ]; then
  echo "==== NORTH R-1 APPARATUS: ALL CELLS MATCHED CONTRACT EXPECTATION ===="
else
  echo "==== NORTH R-1 APPARATUS: UNEXPECTED VERDICT ===="
fi
exit "$FAIL"
