#!/usr/bin/env bb
(require '[clojure.java.io :as io] '[babashka.process :as p] '[clojure.string :as str])
(load-file "cli/dashboard-state.clj")
(load-file "cli/dashboard-collectors.clj")
(load-file "cli/dashboard-render.clj")
(defn fail! [s] (binding [*out* *err*] (println "FAIL" s)) (System/exit 1))
(defn check [p s] (when-not p (fail! s)))
(let [root (.toFile (java.nio.file.Files/createTempDirectory "north-dashboard-live" (make-array java.nio.file.attribute.FileAttribute 0)))
      state-root (io/file root "state") agents (io/file state-root "agents") threads (io/file state-root "threads")
      pid (str/trim (:out (p/sh "bash" "-c" "echo $PPID")))]
  (try
    (.mkdirs agents) (.mkdirs threads)
    (spit (io/file agents "lane-test1.log") "[spawn] starting provider=openai tier=standard (route=standard/medium)\n")
    (spit (io/file agents "lane-test1.lane.pid") (str pid))
    (spit (io/file agents "lane-test2.log") "dead\n")
    (spit (io/file agents "lane-test3.log") "[spawn] starting provider=anthropic tier=senior\n")
    (spit (io/file agents "lane-test3.lane.exit") "0")
    (spit (io/file agents "lane-test4.log") "AGENT_THREAD=thread-fixture\n[spawn] complete (process=ran, delivery=ok)\n")
    (spit (io/file agents "lane-test4.meta.json") "{\"thread\":\"thread-fixture\",\"role\":\"executor\",\"tier\":\"standard\",\"effort\":\"high\",\"provider\":\"openai\",\"model\":\"gpt-5.6-sol\",\"startedAt\":\"2026-08-03T00:00:00.000Z\"}\n")
    (spit (io/file agents "lane-test5.log") "[spawn] complete (process=provider_error, delivery=no)\n")
    (spit (io/file agents "lane-fresh.log") "[spawn] starting provider=openai tier=standard\n")
    (spit (io/file agents "lane-long.log") (str "[spawn] complete (process=ran, delivery=ok)\n" (apply str (repeat 4096 "report "))))
    (spit (io/file agents "lane-stale.log") "[spawn] starting provider=openai tier=standard\n")
    (.setLastModified (io/file agents "lane-stale.log") (- (System/currentTimeMillis) 180000))
    (spit (io/file agents "lane-mutation.log") "worktree provisioned\n[spawn] starting provider=anthropic tier=senior (route=senior/high)\n")
    (spit (io/file agents "lane-mutation.lane.pid") (str pid))
    (spit (io/file threads "thread-fixture-slug.md") "# Joined thread title\n")
    (with-redefs [north.dashboard.collectors/state-dir (.getPath state-root)
                  north.dashboard.state/cache-dir (constantly (.getPath root))]
      (reset! north.dashboard.collectors/log-sizes {})
      (let [by-id (into {} (map (juxt :id identity) (:lanes (north.dashboard.collectors/lanes))))]
        (check (= "advancing" (get-in by-id ["test1" :status])) "first live observation was not working")
        (check (= "advancing" (get-in by-id ["test2" :status])) "first recent observation was not working")
        (check (= "finished" (get-in by-id ["test3" :status])) "exit lane was not finished")
        (check (= "finished" (get-in by-id ["test4" :status])) "managed completion was not finished")
        (check (= "failed" (get-in by-id ["test5" :status])) "managed provider failure was not failed")
        (check (= "advancing" (get-in by-id ["fresh" :status])) "fresh no-pid lane was not working")
        (check (= "finished" (get-in by-id ["long" :status])) "completion beyond tail window was not found")
        (check (= "suspect" (get-in by-id ["stale" :status])) "stale no-terminal lane was not lost")
        (check (= "Joined thread title" (get-in by-id ["test4" :title])) "joined thread title was not extracted")
        (check (= "executor" (get-in by-id ["test4" :role])) "meta role was not extracted")
        (check (= "high" (get-in by-id ["test4" :effort])) "meta effort was not extracted")
        (check (and (= "standard" (get-in by-id ["test1" :role])) (= "medium" (get-in by-id ["test1" :effort])) (= "openai" (get-in by-id ["test1" :provider]))) "legacy spawn metadata missing")
        (check (and (= "senior" (get-in by-id ["mutation" :role])) (= "high" (get-in by-id ["mutation" :effort]))) "mutation spawn metadata was not found on line two"))
      (spit (io/file agents "lane-test2.log") "dead but growing\n")
      (check (= "advancing" (get-in (into {} (map (juxt :id identity) (:lanes (north.dashboard.collectors/lanes)))) ["test2" :status])) "second grown observation was not advancing")
      (let [started (.toString (java.time.Instant/ofEpochMilli (- (System/currentTimeMillis) 720000)))
            many (vec (concat [{:id "work-lane" :thread "019fc335-5c17-77d5-a8e2-38001f8c97f9" :startedAt started :title "Working fixture title" :role "integrator" :effort "high" :provider "openai" :model "gpt-5.6-sol" :status "advancing" :last-output-age 0}
                               {:id "legacy-lane" :role "senior" :effort "high" :provider "anthropic" :status "advancing" :last-output-age 0}
                               {:id "failed-lane" :title "Failed fixture title" :status "failed" :last-output-age 0}]
                              (for [n (range 11)] {:id (str n) :title (apply str (repeat 50 "x")) :status "suspect" :last-output-age n})))
            board "THREADS — 12 open threads · 7 active · 3 ready · 1 blocked\n\nACTIVE\n native-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 019fc335-5c17-77d5-a8e2-38001f8c97f9 Active fixture title\n\nREADY — top 3\n unblocks 2  019fc335-5c17-77d5-a8e2-38001f8c97f9 Low leverage ready\n unblocks 34  019fc336-5c17-77d5-a8e2-38001f8c97f9 High leverage ready\n unblocks 8  019fc337-5c17-77d5-a8e2-38001f8c97f9 Middle leverage ready"
            providers {:providers [{:targets [{:id "openai-main" :routing "eligible" :usage {:windows [{:usedPercent 42 :resetsAt "2026-08-04T10:00:00Z"}]}}]}]}]
        (north.dashboard.state/record! :lanes {:status :ok :data {:lanes many}})
        (north.dashboard.state/record! :health {:status :ok :data {:services {"north-coord.service" {:active true :socket true :memory {"memory.current" "2254857830" "memory.max" "19327352832"}}}}})
        (north.dashboard.state/record! :board {:status :ok :data {:text board}})
        (north.dashboard.state/record! :providers {:status :ok :data providers})
        (let [out (north.dashboard.render/render) lines (str/split-lines out)]
          (check (some #(.contains % "(+2 older)") lines) "fleet row cap summary missing")
          (check (every? #(<= (count %) 100) lines) "line width was not truncated")
          (check (.contains out "Working fixture title") "meta fleet title did not render")
          (check (.contains out "(untitled)") "untitled fleet row did not render")
          (let [fleet (take-while #(not (.startsWith % "HEALTH")) (drop-while #(not (.startsWith % "FLEET")) lines))
                rows (filter #(.contains % "working") fleet)]
            (check (= 1 (count (set (map #(.indexOf % "working") rows)))) "fleet status column drifted")
            (check (not-any? #(re-find #"[0-9a-f]{32,}" %) rows) "fleet task column rendered a lane hash"))
          (check (.contains out "QUEUE") "board header was not renamed")
          (check (re-find #"● 1[12]m  Active fixture title" out) (str "meta-bound live lane did not render active stint: " out))
          (check (and (.contains out "○  High leverage ready") (.contains out "unblocks 34")) "unbound ready row did not render marker and leverage")
          (check (< (.indexOf out "Active fixture title") (.indexOf out "High leverage ready") (.indexOf out "Middle leverage ready") (.indexOf out "Low leverage ready")) "queue ordering was not active then leverage descending")
          (check (and (.contains out "7 active · 3 ready · 1 blocked") (not (.contains out "native-")) (not (re-find #"[0-9a-f]{40,}" out))) "queue was not summarized safely")
          (check (and (re-find #"openai-main +eligible +42%" out) (re-find #"resets (?:[0-9]+[mhd]|now|—)" out)) "providers were not humanized")
          (check (.contains out "working = producing output · done/failed = finished · lost = died without reporting") "footer legend missing")
          (check (not (re-find #"stale" (first (str/split out #"HEALTH")))) "stale leaked into fleet rows")
          (check (re-find #"· data [0-9]+s old" out) "header did not render snapshot age")
          (check (not (re-find #"(?i)suspect|advancing|live quiet" out)) "internal status vocabulary leaked")
          (check (not (.contains out "\u001b")) "NO_COLOR render contained ANSI escape bytes")
          (with-redefs [north.dashboard.render/color? (constantly false)]
            (check (not (re-find #"\u001b" (north.dashboard.render/render))) "NO_COLOR purity failed"))
          (with-redefs [north.dashboard.render/color? (constantly true)]
            (let [colored (north.dashboard.render/render)]
              (check (.contains colored "\u001b[32mworking\u001b[0m") "working row was not green")
              (check (.contains colored "\u001b[31mfailed\u001b[0m") "failed row was not red")))))
      (let [calls (atom 0)]
        (with-redefs [north.dashboard.state/record! (fn [& _] nil)]
          (north.dashboard.collectors/collect! :board #(swap! calls inc))
          (north.dashboard.collectors/collect! :board #(swap! calls inc))
          (Thread/sleep 100)
          (check (= 1 @calls) "board collector overlapped"))))
    (println "dashboard-live: passed")
    (finally (doseq [f (reverse (file-seq root))] (io/delete-file f true)))))
